### ISSUE TITLE
Customize formatting

### ISSUE THREAD

**Issue by angelozerr** [theia-ide/typescript-language-server#10]
tsserver gives the capability to customize formatting. It should be cool if typescript-lsp could provide this same feature. The formatting can be customized by client (eclispe preferences, editorconfig, etc).

**Comment by svenefftinge** [comment]
Currently, I am looking for a `tsfmt.json` in the workspace root.

**Comment by angelozerr** [comment]
> Currently, I am looking for a tsfmt.json in the workspace root.

I didn't know this mean to format, thanks for the info! I think you should add that in the README (or wiki).

Your feature is very nice but I think we should give the capability to customize format for a given file to support editorconfig for instance.

**Comment by gf3** [comment]
it would be cool to allow the use of other formatters, too. for instance the company i work for uses prettier/eslint to format typescript

**Comment by rchl** [comment]
This server does follow the parameters (tabSize, insertSpaces) specified in the `textDocument.formatting` request (see [the code](https://github.com/theia-ide/typescript-language-server/blob/ab7f35b810d37eda33af35819b0145e286c688b4/server/src/lsp-server.ts#L571-L613)) so it's just the responsibility of the client to pass those when triggering the request.

Using other formatters is not really responsibility of this server.

With that said, resolving as WFM.
