### ISSUE TITLE
Using tslint language server plugin without adding it to the workspace

### ISSUE THREAD

**Issue by JSiebelink** [theia-ide/typescript-language-server#100]
I am succesfully using the language server in combination with emacs (spacemacs) and lsp-ui. https://github.com/emacs-lsp/lsp-mode With this, I am trying to use the tslint-language-server as well. However, for it to work I have to add the tslint-language-server as a reference to the tsconfig.json file of my project. Is it possible to somehow use the tslint-language-server without adding it to the plugin field in the tsconfig.json so that I don't have to check it iinto our source control repository? Maybe there is a way that I can use it globally?

Thanks in advance!

**Comment by mickaelistria** [comment]
Since tslint is now deprecated ( https://www.infoq.com/news/2019/02/tslint-deprecated-eslint ), I think this shouldn't be implemented now in the Language Server.

**Comment by rchl** [comment]
You can specify plugins in `initializationOptions`.

The initialization options are defined as:

```ts
export interface TypeScriptInitializationOptions {
    logVerbosity?: string;
    plugins: TypeScriptPlugin[];
    preferences?: UserPreferences;
    hostInfo?: string;
}
```

and `TypeScriptPlugin` is defined as:

```ts
export interface TypeScriptPlugin {
    name: string;
    location: string;
}
```

You have to figure out how to pass `initializationOptions` within your editor but it is supported.

**Comment by samhh** [comment]
@rchl I've got plugins working but only if they're installed locally, not installed globally with `npm i -g`. Any idea why that might be?
