### ISSUE TITLE
Doesn't raise an error/warning about unused variables.

### ISSUE THREAD

**Issue by anurbol** [theia-ide/typescript-language-server#103]
Great library! However it seems to not raise an error or warning when `noUnusedLocals` is set to `true` and there is an unused variable.

**Comment by svenefftinge** [comment]
It usually does. Could it be that the LS is not picking up your tsconfig?

**Comment by rchl** [comment]
Works here:

![Screenshot 2021-07-04 at 21 21 08](https://user-images.githubusercontent.com/153197/124397056-c25b2a80-dd0d-11eb-8e5a-991398f0d575.png)
