### ISSUE TITLE
Mocha tests not running

### ISSUE THREAD

**Issue by theBadT** [theia-ide/typescript-language-server#105]
I've forked the repo, built the sources and am trying to execute the tests. This is currently not working.
![grafik](https://user-images.githubusercontent.com/1228538/54948804-d9f7b600-4f3d-11e9-9894-523c7c391e67.png)
As you can see, nothing much is happening. The server example itself is running perfectly fine.
Any input on this issue?

OS: Windows 10

**Comment by theBadT** [comment]
Additionally when executing the very same tests on a CMD, the following error occurs.
[FailingTest.txt](https://github.com/theia-ide/typescript-language-server/files/3005174/FailingTest.txt)

**Comment by DonnieWest** [comment]
It appears we currently have issues on Windows? #72 

I don't personally use a Windows computer, so I'm closing unless someone else wants to take this on
