### ISSUE TITLE
code completion for html and css within tagged template strings

### ISSUE THREAD

**Issue by nimo23** [theia-ide/typescript-language-server#106]
Please provide "Content Assist/Code Completion" for html and css inside of JavaScript and TypeScript tagged template strings.

For example:

```
..
  render() {
    return html`
     <style>
      p { font-size: 12px;}
     </style>
      <p>${this.myString}</p>
      <ul>
        ${this.myArray.map(i => html`<li>${i}</li>`)}
      </ul>
    `;
  }
```

**Comment by DonnieWest** [comment]
I don't believe this is something supported by `tsserver`, so it's not something we're going to support here
