### ISSUE TITLE
A default set of typescript plugins

### ISSUE THREAD

**Issue by mickaelistria** [theia-ide/typescript-language-server#107]
Wouldn't it make sense to ship this LS with some TypeScript plugins included and enabled by default to best map users's expectations? Namely I'm thinking about Angular, embedded HTML/CSS and similar most popular plugins.

**Comment by rchl** [comment]
No, I don't think the server should have such opinionated logic. That's up to user to customize or up to the editor-specific wrapper to expose that possibility.
