### ISSUE TITLE
Code completion does not work with monaco newer than 0.14.6

### ISSUE THREAD

**Issue by taowen** [theia-ide/typescript-language-server#114]
```ts
import * as path from 'path';
path.join('a', 'b')
```

There should be code completion hint when typing `'path'` and `path.join`.  It works fine with 0.14.6 version, but does not work on newer version. I am not sure this is a typescript-language-server issue or monaco-languageclient issue.

**Comment by akosyakov** [comment]
Make sure to use monaco-languageclient 0.10.0 to support the latest Monaco and LSP. Previous versions does not support Monaco versions greater than 0.14.6.
