### ISSUE TITLE
doesn't support optional-chaining?

### ISSUE THREAD

**Issue by kud** [theia-ide/typescript-language-server#116]
https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining

<img width="340" alt="image" src="https://user-images.githubusercontent.com/655838/63872774-a0c8e380-c9be-11e9-81cd-e91f6e9edc75.png">

**Comment by kud** [comment]
Well. https://github.com/rimeto/ts-optchain

But I'd like to know now how to use a typescript config file for the server. :x

**Comment by bcomnes** [comment]
Getting this as well.

**Comment by danielpza** [comment]
@bcomnes perhaps, can you check your global and local typescript versions? I don't have this problem anymore

```sh
tsc --version
npx tsc --version
```

**Comment by bcomnes** [comment]
Its installed by the sublime text language server, but looks like:

"typescript": "4.2.4",
"typescript-language-server": "0.5.1"

I dont have global or project tsc installed, since I just want language server features on plain js.

**Comment by danielpza** [comment]
@bcomnes I don't have sublime text, I'm using emacs and it's working for me on typescript 4.1.4 and 0.5.1 of this language server.

- can you post an error message given by sublime text?
- do you have a tsconfig.json file, if yes can you post it?

**Comment by bcomnes** [comment]
I don't have a tsconfig file since the project isn't a typescript project.  I could add one though.

Does typescript run in a older version of the language without one?

**Comment by rchl** [comment]
Try with `tsconfig.json`:

```js
{
    "compilerOptions": {
        "baseUrl": ".",
        "target": "esnext",
        "module": "esnext",
        "esModuleInterop": true,
        "moduleResolution": "node",
        "noEmit": true,
        "allowJs": true,
        "checkJs": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "resolveJsonModule": true,
        "lib": [
            "dom",
            "esnext",
        ],
}
```

(the project doesn't have to be written in typescript for this to work)

**Comment by danielpza** [comment]
@bcomnes are you using react or jsx?

**Comment by bcomnes** [comment]
Yes, this in a .jsx file.

**Comment by rchl** [comment]
You need to open a folder in ST and in the root of the folder there needs to be `tsconfig.json`. It works for me this way, even for *.jsx file.

**Comment by rchl** [comment]
WFM.

You can  create a reproduction project if it doesn't for you.

**Comment by bcomnes** [comment]
> You need to open a folder in ST and in the root of the folder there needs to be `tsconfig.json`. It works for me this way, even for *.jsx file.

I tried that with the same result. 

> WFM.
> 
> You can create a reproduction project if it doesn't for you.

No problem, I've not had a chance to revisit the project in question.  I'll reopen an issue with a reproducible example if I revisit.
