### ISSUE TITLE
Completion not filtering/sorting by prefix

### ISSUE THREAD

**Issue by brainoutsource** [theia-ide/typescript-language-server#118]
Hello! I'm working on a tool which uses `typescript-language-server` among other LSPs.

Diagnostics work fine, but I'm having trouble (or am I?) with the way completion works. Consider the example:

1) I invoke completion (`|` is the position of the cursor I send with `CompletionParams.Position`):

```
document.body.|textContent = user; 
```

and get all kinds of relevant stuff, starting with `accessKey`, and including the `textContent`.

2) Now I invoke the completion here:

```
document.body.tex|tContent = user; 
```

and I get the very same result, not filtered or sorted by the `tex` prefix.

Is it an expected behaviour? Is it LSP client's job to sort/filter the completion suggestions? Thank you!

Btw, [sourcegraph/javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver) displays the same behaviour.

**Comment by pengsongkun741** [comment]
This seems to be the case with most grammar services now. Include Css and HTML language services in Vsode.
The normal practice should be to filter and sort the data after it is received. But it’s even better if you deal with the language on the server side

**Comment by rchl** [comment]
This can't be handled on the server side. Client (editor) has to do it.

With a case like:
```
document.body.tex|tContent = user; 
```
if the server would filter out all completions that don't start with `tex` then once the user would delete `x`, he would no longer see suggestions since completions are not re-requested on modifying the trigger text.
