### ISSUE TITLE
typescript-tslint-plugin on Javascript files

### ISSUE THREAD

**Issue by theFroh** [theia-ide/typescript-language-server#119]
G'day, it appears that `typescript-tslint-plugin` diagnostics aren't appearing in Javascript files.

Even with the language server itself recognising and providing `tsserver` diagnostics on a well behaved TS+JS project, this doesn't seem to include the diagnostics that the `tslint` plugin would inform us of.

Not quite sure if this is a limitation due to implementation of the language server, but my only point of cross-reference is against VSCode's own diagnostics, which definitely do supply `tslint` notes on Javascript.

Cheers!

**Comment by DonnieWest** [comment]
#159 since tslint is deprecated,  closing this
