### ISSUE TITLE
dependencies completion in package.json

### ISSUE THREAD

**Issue by mickaelistria** [theia-ide/typescript-language-server#126]
Some user of Wild Web Developer is requesting completion for dependencies (id, versions) in package.json, querying npm.js. Is this something that would be in the scope of this language server and a viable enhancment request? In any case, are you aware of some language server that would provide that?

**Comment by akosyakov** [comment]
I don't think it is related to javascript/typescript languages. You will need to implement npm language server which is interested in package.json files. It should not be hard. You can copy an implementation from here: https://github.com/microsoft/vscode/blob/master/extensions/npm/src/features/packageJSONContribution.ts and adjust it to LSP completions API.
