### ISSUE TITLE
Support Typescript v3.7 syntax

### ISSUE THREAD

**Issue by pragmasoft-ua** [theia-ide/typescript-language-server#136]
Currently I'm getting a syntax error, when safe navigation ?. operator is used.

**Comment by martinheidegger** [comment]
Noticed that this is a duplicate of #116

**Comment by apexskier** [comment]
I'm not having any issue with this in https://github.com/apexskier/nova-typescript/, which uses this language server.

**Comment by rchl** [comment]
Yeah, I think the original poster had an issue with either using very old `typescript` dependency in his project or not setting up `compilerOptions.target` to recent enough target.
