### ISSUE TITLE
looking for maintainers

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/typescript-language-server#141]
Theia moved to use VS Code extension directly to keep pace with VS Code. Unfortunately it means that Theia commiters cannot dedicate their time to maintain this project anymore.

Who will be willing to step up and keep maintaining this project? You will be granted admin rights on this repo and invited as a collaborator on npmjs to allow package publishing.

**Comment by DonnieWest** [comment]
@akosyakov I'd be willing to maintain until `tsserver` implements [this natively](https://github.com/microsoft/TypeScript/issues/39459#issuecomment-697622569)

Do you have a process for handoff? I'm also willing to chat privately to answer any questions you might have :)

**Comment by predragnikolic** [comment]
This is not the true? ⬇️

![Screenshot_20201002-220627_Chrome](https://user-images.githubusercontent.com/22029477/94965386-acf56d80-04fb-11eb-95d0-f45bb8adb048.jpg)

Right? 😂

**Comment by DonnieWest** [comment]
I've been given maintainership rights, so time to close this :+1:

**Comment by lzaaldian** [comment]
Awesome @DonnieWest 🙌 Thank you for willing to continue supporting this repo.

**Comment by NullVoxPopuli** [comment]
If this has moved to VS Code, what are all the other editors supposed to do? :-\

**Comment by rchl** [comment]
@DonnieWest would you like some help with this server? I could help handling some PRs at least.

I know that Microsoft is supposed to come up with official implementation sooner or later but I think that is not a reason to just stop improving this one. At least until the official one is out and proven to work better in every way.)

(I'm one of the maintainers of the [Sublime Text LSP](https://github.com/sublimelsp/LSP))

**Comment by DonnieWest** [comment]
@rchl hey, thanks for volunteering! I'd super appreciate some help

If it's alright with you, I'll see if I can get you added onto the repo like I am

**Comment by rchl** [comment]
@DonnieWest sounds good

**Comment by rchl** [comment]
@DonnieWest I don't have other means of contacting you so doing it here. Would you (and original maintainers) be fine with also giving me npm publishing privileges? We have some nice fixes lined up for release and it would be good to get those and future fixes out more often.
