### ISSUE TITLE
Adding additional options for tsserver's `configure` request

### ISSUE THREAD

**Issue by romandecker** [theia-ide/typescript-language-server#143]
Hey there!

I'm looking to support more options (mainly `importModuleSpecifier`, but theoretically any of the options defined [here](https://github.com/microsoft/TypeScript/blob/master/src/server/protocol.ts#L3142-L3168)) for `tsserver`'s `configure` request. I see that you already send a `configure` request as part of the initialization phase, so it should be relatively simple to add more options there.

I'm happy to implement it myself - would you accept a PR for this?

**Comment by PyvesB** [comment]
> I'm happy to implement it myself - would you accept a PR for this?

The project is looking for additional maintainers - see here: https://github.com/theia-ide/typescript-language-server/issues/141 :wink:

**Comment by DonnieWest** [comment]
If you're still interested, I'm accepting PRs :)

**Comment by blahgeek** [comment]
+1 for this!

Also, currently the `includeExternalModuleExports` and `includeInsertTextCompletions` options are always set in completion request in https://github.com/theia-ide/typescript-language-server/blob/3a8ea0f04bde047e2f60b9f68ef7816e3a41aa10/server/src/lsp-server.ts#L444. They are deprecated and user preferences should be used instead. If we can support additional options for configure request, we should also remove them.

**Comment by romandecker** [comment]
Hello there,

sorry to disappoint - due to other obligations I won't have time to implement a PR for this - I actually had to move away from `typescript-language-server` and am just using vscode atm.

So anybody is welcome to pick this up and start working on it!

**Comment by apexskier** [comment]
This is resolved by https://github.com/theia-ide/typescript-language-server/pull/218.

**Comment by rchl** [comment]
Agreed.

Also handling the issue mentioned in https://github.com/theia-ide/typescript-language-server/issues/143#issuecomment-787042664 in https://github.com/theia-ide/typescript-language-server/pull/233
