### ISSUE TITLE
Can tsserver reveal the type behind <any>?

### ISSUE THREAD

**Issue by steveeq1** [theia-ide/typescript-language-server#164]
Sometimes I set variables to type <any> when I am playing around. However, is there any way for tsserver to tell me what "type" this <any> variable has? Like if I hover the cursor over "any" or the variable itself, it shows me the "type"?

I am using emacs with lsp and lsp-ui modes.

**Comment by DonnieWest** [comment]
Sorry, I don't think this is possible
