### ISSUE TITLE
bind does not exists on type (s:string)=>void

### ISSUE THREAD

**Issue by NikosEfthias** [theia-ide/typescript-language-server#165]
I get no compilation error however the lang server says bind doesnt exist under a function 
```
src/index.tsx|20 col 35| typescript:Error:2339:Property 'bind' does not exist on type '(s: string) => void'.
```

**Comment by rchl** [comment]
You probably would need to provide a reproduction repo if you expect someone to help you.

**Comment by NikosEfthias** [comment]
seems adding es2015 to the lib fixes this issue
