### ISSUE TITLE
cli options broken

### ISSUE THREAD

**Issue by tbo** [theia-ide/typescript-language-server#17]
The follwing cli options don't seem to work for me:

```
--log-level
--tsserver-logFile 
--tsserver-path
```

I had a look at `src/cli.js` and I cannot see how this could have ever worked. My findings:

 -  `log-level` is interpreted as boolean flag, because it has no parameter assigned
 - Typo at line at line 29: `program['leg-level']`
 - The description for `--tsserver-logFile` is spelled differently: `--tsServerLogFile=ts-logs.txt` (both don't work)

I tried to build a PR for this, but encountered additional problems. Even if I hard-code my configuration in `cli.js` and pass it directly to `createLspConnection`, no logs a being created. I think, that the server options aren't properly set in the constructor of `LspServer`. Some methods are using `this.options`, but I cannot find where it is being set.

This part still works in @prabirshrestha's repo.

**Comment by svenefftinge** [comment]
Thanks for the report. Are you going to create a PR or did you give up?

**Comment by tbo** [comment]
I would be open to create a PR with my improvements to `cli.js`. But I currently cannot invest enough time to debug this further. Maybe we can collaborate on this?

**Comment by svenefftinge** [comment]
Of course, I just wanted to understand what part you are going to work on, so we don't do the same work. :)

**Comment by tbo** [comment]
There might be a misunderstanding. I just fixed the handling of cli arguments in my PR, but they are still not properly applied. So this issue is still persists.

**Comment by svenefftinge** [comment]
Yes, I know. I'm on it. Just wanted to have the fix for 'log-level' already. (I got interrupted, as I'm at a conference this week). I will finish it in the next days and than make a release. Thank you!
