### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by chasecaleb** [theia-ide/typescript-language-server#177]
Thanks for taking over maintainership, @DonnieWest! I see there have been a number of commits over the past few months but no new release tag here or version on npm. Do you have plans for that, or should I start building it myself from master?

By the way, you might want to add yourself as the maintainer in the readme since it's out of date.

**Comment by aca** [comment]
@DonnieWest You are my savior

**Comment by CarlQLange** [comment]
I would also love to see a new release, do you think there's something I or another interested person could do to help get you there?

**Comment by DonnieWest** [comment]
0.5.0 published

**Comment by DonnieWest** [comment]
Err, 0.5.1 because of local env silliness. Apologies

**Comment by CarlQLange** [comment]
Thank you so much, and fantastic job!
