### ISSUE TITLE
Duplicate items are included in the completion candidates.

### ISSUE THREAD

**Issue by nabezokodaikon** [theia-ide/typescript-language-server#178]
Duplicate items are included in the completion candidates.

<img width="488" alt="スクリーンショット 2020-12-19 20 22 31" src="https://user-images.githubusercontent.com/3197942/102688132-f40c1880-4237-11eb-9eb5-7f0b0ba918e7.png">

tsconfig.json
```json
{
  "compilerOptions": {
    "lib": ["es2015"],
    "module": "commonjs",
    "outDir": "dist",
    "sourceMap": true,
    "strict": true,
    "target": "es2020"
  },
  "include": [
    "src/**/*"
  ]
}
```

#### Expected behavior
The completion candidates should not contain duplicates.

**Comment by rchl** [comment]
Try to insert those completion and see if those insert different imports. I think one is for `fs` module and another for `fs-extra`.

**Comment by nabezokodaikon** [comment]
Currently there seems to be no duplication. Thank you very much.

**Comment by rchl** [comment]
And there is #123 to improve the presentation so closing this one.
