### ISSUE TITLE
Support for completion auto import

### ISSUE THREAD

**Issue by angelozerr** [theia-ide/typescript-language-server#18]
Since today with `npm install typescript@next` you can support completion with auto import that I'm implementing inside [typescript.java](https://github.com/angelozerr/typescript.java)

![autoimportdemo](https://user-images.githubusercontent.com/1932211/31760404-e2694ad0-b4b4-11e7-9b98-cfe28bc50f87.gif)

It should be fantastic if `typescript-language-server`  could support it. Here tsserver traces:

TypeScript request#completionEntryDetails: 
```json
{
	"command": "completionEntryDetails",
	"arguments": {
		"entryNames": [
			"PI"
		],
		"line": 1,
		"offset": 3,
		"file": "C:/Users/azerr/WS2/___aa/b.ts"
	},
	"seq": 9,
	"type": "request"
}
```

TypeScript response#completionEntryDetails with 61ms: 

```json 
{
	"seq": 0,
	"type": "response",
	"command": "completionEntryDetails",
	"request_seq": 9,
	"success": true,
	"body": [
		{
			"name": "PI",
			"kindModifiers": "export",
			"kind": "const",
			"displayParts": [
				{
					"text": "const",
					"kind": "keyword"
				},
				{
					"text": " ",
					"kind": "space"
				},
				{
					"text": "PI",
					"kind": "localName"
				},
				{
					"text": ":",
					"kind": "punctuation"
				},
				{
					"text": " ",
					"kind": "space"
				},
				{
					"text": "3.14",
					"kind": "stringLiteral"
				}
			],
			"documentation": [],
			"tags": [],
			"codeActions": [
				{
					"description": "Import 'PI' from \"./a\".",
					"changes": [
						{
							"fileName": "C:/Users/azerr/WS2/___aa/b.ts",
							"textChanges": [
								{
									"start": {
										"line": 1,
										"offset": 1
									},
									"end": {
										"line": 1,
										"offset": 1
									},
									"newText": "import { PI } from \"./a\";\r\n\r\n"
								}
							]
						}
					]
				}
			]
		}
	]
}
```

**Comment by Akin909** [comment]
I would be happy to have a go at adding in this functionality (if no one is already working on it) as we are looking to switch to using your awesome project in [`oni`](https://github.com/onivim/on), although I'd very much appreciate a hint re where and how to start when looking to implement this.

**Comment by svenefftinge** [comment]
Hey @Akin909 
I am not aware of anyone started working on this. I'd like to see that feature very much. 
It is just that so far the import fixes coming from tsserver are not always good, at least not in more complex settings (e.g. yarn workspace mono-repos).
If that is still the case, we might have to use a preference to enable this feature.

**Comment by euclio** [comment]
Sounds like the work here is to translate the codeActions to additionalTextEdits?

**Comment by dylan-chong** [comment]
Hello all, hopefully this issue is not completely dead. Importing is such a useful feature to have, and would make this package really complete (if you pardon the pun).

I just found this link about microsoft implementing auto-import on completion which got closed october 2017. Thought it would be useful https://github.com/Microsoft/TypeScript/issues/7849.

**Comment by akosyakov** [comment]
Resolved by https://github.com/theia-ide/typescript-language-server/pull/50
