### ISSUE TITLE
callsProvider in server capabilities returned by initialize request

### ISSUE THREAD

**Issue by pajatopmr** [theia-ide/typescript-language-server#188]
I am writing an LSP client and the response to the initialize request contains an unexpected callsProvider element. I am writing my client to version 3.16 of the LSP spec. Is this not a typescript-language-server bug? Or perhaps my client capabilities being passed is not up to par --- missing something maybe?

**Comment by rchl** [comment]
This doesn't seem to be a capability defined by the spec but it shouldn't be a problem for the client as the client should ignore unknown capabilities.
