### ISSUE TITLE
PNP Support?

### ISSUE THREAD

**Issue by Jaden-Giordano** [theia-ide/typescript-language-server#193]
I'm not sure if my setup is the problem or if yarn plug n' play isn't supported. I can't seem to get module's to resolve in a yarn 2 environment. I tried using the yarn sdk's (https://yarnpkg.com/getting-started/editor-sdks#emacs) aswell to see if It was that but it still is unable to resolve any of my installed dependencies. The project runs fine; I'm using the default vue w/ typescript from vite. I can provide more information but I wanted to see if maybe it just wasnt supported yet first.

**Comment by Jaden-Giordano** [comment]
It seems like its hardcoded to look into the `node_modules` directory for the module resolution (https://github.com/theia-ide/typescript-language-server/blob/master/server/src/modules-resolver.ts#L14). I'm looking into a way we could resolve pnp modules by checking if the environment is a yarn pnp env (if the `.pnp.js` file exists or something).

**Comment by rchl** [comment]
`require.resolve` would probably work regardless.
Checkin for `.pnp.js` or other such specific solutions don't sound right.

**Comment by rchl** [comment]
@DonnieWest do you think we could release current changes? The removal of timeout and this are important enough changes IMO

**Comment by tapayne88** [comment]
Unfortunately I don't _think_ this was resolved with #195, or at least it hasn't been resolved for neovim native LSP. @Jaden-Giordano does this fix your emacs setup (assuming that's what you're using)?

**Comment by DonnieWest** [comment]
@tapayne88 good point. Thanks

**Comment by rchl** [comment]
OK, let's get the actual yarn PNP fix (#220) in before releasing but that needs a bit more testing.

**Comment by DonnieWest** [comment]
@rchl Woops, missed that your other comment was also here

I'm still on board with releasing. I agree that the other changes are pretty important and it would be nice to let #220 simmer a bit longer

**Comment by rchl** [comment]
I agree. Let's do that.

**Comment by rchl** [comment]
We're assume that #220 fixes it until proved otherwise.

**Comment by Hubro** [comment]
Is there anything I need to do to make `typescript-language-server` work with Yarn v3 and PNP? I have a project with all dependencies installed, and I installed `typescript-language-server` like this:

```
> npm install -g typescript-language-server
```

When I start the language server in Neovim, it's clear that it can't find any of my dependencies:

![image](https://user-images.githubusercontent.com/597206/163609034-f956ef3c-4df1-45f7-9c33-4de76118b52d.png)

```
➜ typescript-language-server --version
0.9.7
```

**Comment by greym0uth** [comment]
@Hubro You may need to check https://yarnpkg.com/getting-started/editor-sdks to get it setup with vim

**Comment by Hubro** [comment]
Ah, you're right... That's confusing.

**Comment by cybermelons** [comment]
Make sure to add `typescript` and `typescript-language-server` to your `package.json` before installing the yarn sdks

```bash
yarn add -D typescript typescript-language-server
yarn dlx @yarnpkg/sdks base
# now you should see `.yarn/sdks/typescript-language-server`
```

I was using a monorepo with sub-packages in `packages/mypackage`, but kept getting the 'cannot find module' in my subpackages. I am using neovim configured with`nvim-lspconfig`. Doing the above fixed the issue

**Comment by strogonoff** [comment]
@cybermelons In my Neovim containerized LSP server config, I need to supply the actual command to invoke `typescript-language-server --stdio`. Do you know by chance how to do it when it’s installed in `.yarn/sdks`? For some reason it’s a directory and there seems to be no binary anywhere inside.

**Comment by strogonoff** [comment]
My above workaround is no longer working as of Yarn 4.0.1 (with Yarn reporting `"Required package missing from disk"`), but still works as of 3.6.1. `typescript-language-server` version 3.3.6.
