### ISSUE TITLE
Is applyFileRename operational?

### ISSUE THREAD

**Issue by dennisfrostlander** [theia-ide/typescript-language-server#199]
Just a question - is [applyFileRename](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/commands.ts#L13) refactoring operational?
Do I understand it correctly that this command is supposed to change all import references to the file being renamed?

I've tried to invoke this refactoring [like this](
https://github.com/cenk1cenk2/nvim/blob/5ce2d090e5ceb5617a27e1e93fe2d3306ced2268/lua/lsp-language-configurations/tsserver.lua#L17-L45), but I can't get the references to get updates...

**Comment by rchl** [comment]
These are the parameters for that command:

```ts
export interface RenameParams extends WorkDoneProgressParams {
    /**
     * The document to rename.
     */
    textDocument: TextDocumentIdentifier;
    /**
     * The position at which this request was sent.
     */
    position: Position;
    /**
     * The new name of the symbol. If the given name is not valid the
     * request must return a [ResponseError](#ResponseError) with an
     * appropriate message set.
     */
    newName: string;
}
```

If your client implements the standard `textDocument/rename` request then you can use that instead.

**Comment by rchl** [comment]
Are you able to log server communication?
The command should return file editors that the client has to apply. Are those edits not provided or is the client failing to apply them?

**Comment by rchl** [comment]
Triggering this command this way worked:

```
workspace/executeCommand: {
  'command': '_typescript.applyRenameFile',
  'arguments': [
    {
       'sourceUri': 'file:///Users/me/file1.js',
       'targetUri': 'file:///Users/me/file2.js'
     }
   ],
}
```

The references to the file1 were changed. The file itself wasn't renamed though. I guess the expectation is that this command is triggered after trigger manual rename of the file.

**Comment by rchl** [comment]
I don't know that vim scripting at all but you seem to be checking `nvim_buf_is_loaded` which probably means that changes in non-opened files won't be processed. Maybe that's the issue for you?

Anyway, let me know if you find some issues in the current implementation. At this point it seems to me that it works as expected.
