### ISSUE TITLE
Support for typescript.tsdk with tsserverPath

### ISSUE THREAD

**Issue by angelozerr** [theia-ide/typescript-language-server#2]
Like I had written at https://github.com/prabirshrestha/typescript-language-server/issues/6

IMHO I think there are 2 problems with the tsserverPath:

 * By default `tsserver.bat` / `tsserver` is searched in the %PATH (when you install TypeScript in global npm registry). In my case I had a very old installed TypeScript and I was not able to consume navtree. I think `tsserver.bat` / `tsserver`  should be searched at first time with require.resolve like this:

```
try {
    var tsserverPath = require.resolve(".bin/" + (utils.isWindows() ? 'tsserver.cmd' : 'tsserver'));
    this.options.tsserverPath = tsserverPath;        	
}
catch(error) {}

 this.tsServerClient = new tsServerClient_1.TsServerClient({
            tsserverPath: this.options.tsserverPath || (utils.isWindows() ? 'tsserver.cmd' : 'tsserver'),
            logFile: this.options.tsserverLogFile,
            logger: this.logger
        });
```
 * IMHO I think it should be better to consume typescript/lib/tsserver.js to provide a `typescript.tsdk` settings (your tsserverPath) like VSCode does https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

It will be more easy to use it with VSCode.

**Comment by svenefftinge** [comment]
My plan was to find and use the `tsserver` of the current project, by looking into the node_modules of the parent dirs.

**Comment by svenefftinge** [comment]
As I don't have a windows system it would be really awesome if you could try to figure out what is wrong.

**Comment by angelozerr** [comment]
After some test, it seems that in `Windows OS` you cannot execute the `typescript/bin/tsserver`.

To support Windows OS, you must execute `typescript/lib/tsserver.js` with `node`

In other words do like this:

`this.tsserverProc = cp.spawn("node", ["YOUR_PROJECT/node_modules/typescript/lib/tsserver.js"]);`

**Comment by svenefftinge** [comment]
ok, thanks for checking. Should not be too hard to have the alternative case for windows, then.
Ar you going to take a crack at it?

**Comment by svenefftinge** [comment]
So is the `tsserver.cmd` file only present when you install typescript using the installer, but not part of an install via npm on windows?

**Comment by angelozerr** [comment]
When I do `npm install typescript` in `MY_PROJECT` folder, I have that:

* MY_PROJECT
  * node_modules
    * .bin
      * tsserver.cmd
      * tsserver
    * typescript
      * bin
      * lib

I think you should have the same behaviour with Unix.

To support with clean mean tsserver with any OS, you have 2 choices 
 
 * execute tsserver.cmd for windows and tsserver for other OS which is hosted inside `.bin` folder:

`this.tsserverProc = cp.spawn("YOUR_PROJECT/node_modules/.bin/tsserver.cmd"...`

 * execute tsserver.js  with node :

`this.tsserverProc = cp.spawn("node", ["YOUR_PROJECT/node_modules/typescript/lib/tsserver.js"]);
`

Those 2 solutions should work with any OS.

**Comment by prabirshrestha** [comment]
You need to change this so that if on windows it uses `tsserver.cmd` instead of `tsserver`.

```typescript
const path = findPathToModule(this.rootPath(), 'typescript/bin/tsserver')
return path || 'tsserver'
```

I would have something like this.

```typescript
function getDefaultTsserverBinFile() {
    return isWindows() ? 'tsserver.cmd' : 'tsserver';
}

const defaultTsserverBinFile = getDefaultTsserverBinFile();
const path = findPathToModule(this.rootPath(), path.join('typescript/bin', defaultTsserverBinFile))
return path || defaultTsserverBinFile
```

This is something similar to the PR I sent earlier. https://github.com/theia-ide/typescript-language-server/pull/8

**Comment by svenefftinge** [comment]
Thanks, this should work, no? 
https://github.com/theia-ide/typescript-language-server/pull/11

**Comment by angelozerr** [comment]
> Thanks, this should work, no?

Yes #11 works like a char in Windows.

Today tsserver.cmd is searched with 2 means:

 * in `MY_PROJECT/node_modules/typescript/.bin/tsserver.cmd`
 * in `tsserver.cmd` which means that `npm install -g typespcript` was done.

I think a last strategy should be added:

* search the typescript bundle which is in the same node_modules than typescript-language-server (when you install typescript-language-server with npm). In my case I need that, because I would like to provide an Eclipse plugin https://github.com/mickaelistria/eclipse-bluesky/ which embeds typescript-language-server. When user install the Eclipse plugin and opens a ts or js files, it should work:

 * without installing typescript with  `npm install typespcript` or with  `npm install -g typespcript`

**Comment by svenefftinge** [comment]
The strategy to lookup in the typescript-language-server node_modules would already always find it. The language server wouldn't work if there was no typescript. So what should be the correct order?
I propose:
 - workspace (node_modules)
 - global install (i.e. `tsserver` is on path)
 - shipped with typescript-language-server
