### ISSUE TITLE
`textDocument/formatting` fails with error: `Cannot read property 'insertSpaces' of undefined`

### ISSUE THREAD

**Issue by siegel** [theia-ide/typescript-language-server#200]
I'm working on a new LSP client, and I'm finding that when I send the `textDocument/formatting` request, it fails, and the error report from the server is: `Cannot read property 'insertSpaces' of undefined.`

I did a little experimentation, and found that even if I omit the `insertSpaces` parameter, I get the same error from the server.

The symptom seems to be specific to this server; I've tested `textDocument/formatting` with other servers and it appears to behave as expected with the `insertSpaces` parameter that I provide.

I've started the server using `--stdio --tsserver-log-verbosity=verbose --log-level 4 --tsserver-log-file /tmp/tsserver-log.txt`, so I have attached both `tsserver-log.txt` as well as log output from my client (which captures `stderr` from the server). The file that I opened is also attached.

Is there something specific that the server's looking for in a `textDocument/formatting` request that I'm not providing?

Thanks very much for any advice you can provide.

Server version: 0.5.1
Platform: macOS 10.15.7

[tsserver-log.txt](https://github.com/theia-ide/typescript-language-server/files/6266242/tsserver-log.txt)
[LanguageServerProtocol-JavaScript.log](https://github.com/theia-ide/typescript-language-server/files/6266244/LanguageServerProtocol-JavaScript.log) (The log from the LSP client.)
[prototype.js.zip](https://github.com/theia-ide/typescript-language-server/files/6266247/prototype.js.zip) (Zipped example file)

**Comment by rchl** [comment]
You need to specify your formatting options in an `options` object:
```ts
interface DocumentFormattingParams extends WorkDoneProgressParams {
	/**
	 * The document to format.
	 */
	textDocument: TextDocumentIdentifier;

	/**
	 * The format options.
	 */
	options: FormattingOptions;
}
```

You are providing them in the `params` themselves.

```
2021-04-06 12:25:18.516: Server message: [lspserver] documentFormatting {
  "insertSpaces": false,
  "trimTrailingWhitespace": false,
  "textDocument": {
    "uri": "file:///Users/siegel/svn/trunk/Redacted/LanguageModules/JavaScript/testfiles/prototype.js"
  },
  "tabSize": 4,
  "insertFinalNewline": false
} /Users/siegel/svn/trunk/Redacted/LanguageModules/JavaScript/testfiles/prototype.js
```

**Comment by siegel** [comment]
Thanks for the catch — I think at some point in the past three months I actually figured this out and made an appropriate fix. My apologies for not updating the case, and I appreciate the response.
