### ISSUE TITLE
Javascript: Jump to declaration still not at JSDT's level

### ISSUE THREAD

**Issue by MonNomIzNoGoud** [theia-ide/typescript-language-server#203]
Hi,

I posted this issue in Wild Web Developer and they told me it concerns Language Server. So here's my message:

Hi,
I've been stuck with Eclipse Luna for years now, because of it being (along with Mars) the last version where JSDT worked fine (syntax coloring unbroken).

Your tool seems finally to get close to JSDT in certain aspects, surpass it in others.

But really: the most useful feature in a tool like this (even more important than syntax coloring) is the Jump to declaration ! How can anyone work without it when the project becomes more and more complex ?

And WWD doesn't come close the JSDT regarding Jump to declaration. Or I'm missing something. It works in the same file, when there are prototype functions, but look at this example:

(function ()
{
var global = this || window;
var _Ctrls = null;
_Ctrls = global.Ctrls =
{
test: function()
{
//////
},
test2: function()
{
_Ctrl.test();
}
};
})

Typing F3 (Jump to declaration) on the test() call would give a message like "The operation is not applicable to the current selection etc..."
In JSDT it would take me to the test function declaration. It would even take me to it when called in another javascript file in the same project !

Can anyone tell if this a final behavior or is there a chance to fix it ?

Regards

**Comment by MonNomIzNoGoud** [comment]
Can someone please say if this issue could be resolved or not ?

**Comment by danielpza** [comment]
@MonNomIzNoGoud jump to declaration is working for me on emacs, not for your example though. Have you tried with another code examples?:

```ts
const a = 'foo';

console.log(a); // hovering on `a` and pressing my jump to definition key goes correctly to the first line
```

**Comment by MonNomIzNoGoud** [comment]
@danielpza Yes it works as long as you're in the same file. In a Web project on Eclipse it doesn't work when you have the definition in another Javascript file. Plus it does not work for the example I gave even if it's in the same file.

**Comment by MonNomIzNoGoud** [comment]
For instance, if you declare the following function in file A.js

`var Util =
{
  myFunction: function() {}
}`

And call it in file B.js

`Util.myFunction();`

Then jump to declaration would work in JSDT, but not in Willd Web Developper

**Comment by danielpza** [comment]
Perhaps this can help you https://stackoverflow.com/questions/47794338/typescript-how-to-declare-global-variable-in-every-file?noredirect=1&lq=1

**Comment by MonNomIzNoGoud** [comment]
I've tried importing/exporting and it doesn't work. For example
file1.js
`var Util =
	{
		func1 function(str, delimiter) {
		}
	}
export { Util };`

file2.js
`import { Util } from 'utils.js';

function IndicsViewer(options)
{
	Util.func1();
}
`

And cannot jump to declaration for func1.

I haven't tried the declare keyword or the .ts files. With hundreds of function this just isn't right.

No choice but to stick to JSDT in Eclipse...

**Comment by danielpza** [comment]
This language server relies on typescript, this kind of feature wont probably be implemented here. You can try creating an issue on the typescript repo but I doubt they'll implement something like this since they already have a solution, using the declaration files.

**Comment by MonNomIzNoGoud** [comment]
OK thanks for your answers @danielpza.
I really think that it's up to the Wild Web Developer team to find a solution. Their usage of these modules must include a transparent  way for users to benefit from the typescript solution

**Comment by rchl** [comment]
This issue seems to stem from not using proper module system like CommonJS or ES Imports so nothing this server can do about.
