### ISSUE TITLE
Autocompletion support for Axios TS

### ISSUE THREAD

**Issue by Vanderscycle** [theia-ide/typescript-language-server#214]
Hi,

I'm fairly new to JS/TS but I did notice that the [axios](https://github.com/axios/axios) package works fine in JS but autocomplete is not present in TS.

Simple example in JS
![axios](https://user-images.githubusercontent.com/52706578/118137209-ce83d500-b3b9-11eb-9095-481c0016ee20.png)
Same lines in TS
![axiosTS](https://user-images.githubusercontent.com/52706578/118137215-cfb50200-b3b9-11eb-9570-a4debca085bd.png)

**Comment by danielpza** [comment]
Hello @Vanderscycle , autocomplete seems to be working for me but using `import`s instead of `require`

![image](https://user-images.githubusercontent.com/17787042/118157088-1e799080-b3e8-11eb-8106-b2e86cb11a96.png)

**Comment by danielpza** [comment]
I also tried this with vscode and it's not working with `require` either:

![image](https://user-images.githubusercontent.com/17787042/118157533-ab244e80-b3e8-11eb-8b9c-16e19da72dcd.png)

**Comment by Vanderscycle** [comment]
It works! Thank for your help, I'm slowly moving away from Python.
