### ISSUE TITLE
Multiple and wrong definition

### ISSUE THREAD

**Issue by timsofteng** [theia-ide/typescript-language-server#216]
Hello. I use typescript-language-server with neovim native lsp.
When I'm trying to go to definition it works but it also opens quickfix-list with two files with right one and another strange file something like that
`node_modules/@types/react/index.d.ts|547 col 9| (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;`
![image](https://user-images.githubusercontent.com/51912173/120691038-a36b3d80-c4ae-11eb-8335-73162eee2a6b.png)

My definition is `UsageAndPlan` constant which returned as well but with wrong one definition.

Here is closed issue in nvim repo. So problem is in server.
https://github.com/neovim/neovim/issues/14713

**Comment by DonnieWest** [comment]
@timsofteng I'm not really sure what I'm seeing here. Can you provide a sample project and a means of recreating your issue?

**Comment by timsofteng** [comment]
> @timsofteng I'm not really sure what I'm seeing here. Can you provide a sample project and a means of recreating your issue?

Here is video.

I believe this occurs when you `go-to-definiton` from FC to FC component.
Take a look at the screencast please.

https://user-images.githubusercontent.com/51912173/122251637-5be3a900-ced3-11eb-987e-b9fa77f06857.mp4

node12

Steps to reproduce:
1.Create parent component with `FC` type.
2. Create child component with `FC` type.
3. Return child from parent.
3. Invoke `go-to-definiton` to child from parent.

It will send two definiton.
One is target file and another is interface of `Functional Component`.

**Comment by DonnieWest** [comment]
@timsofteng please provide a sample project that I can test this in

**Comment by timsofteng** [comment]
@DonnieWest 
https://github.com/timsofteng/typescript-lsp-server-bug-test

Clone it.
cd
yarn install
open this component
try to go to definition as on screencast
![image](https://user-images.githubusercontent.com/51912173/122266427-74a78b00-cee2-11eb-87b8-992c4d7b7b4c.png)

**Comment by rchl** [comment]
Note that in the neovim issue they said:

> File an upstream bug with tsserver if you are unhappy with the results returned.

tsserver is not this LSP server. tsserver is an internal server of the `typescript` package.
And I would agree that the behavior comes from there and not this project which just returns whatever tsserver returns.

Personally I don't know if this is expected behavior or not but it's certainly not wrong in any sense since your `BlaChild` has type `FC<BlaParentType>` where the `FC` is the `FunctionComponent` interface and that is where the definition takes you.

**Comment by timsofteng** [comment]
_sorry i just close the issue by mistake_

**Comment by timsofteng** [comment]
> Personally I don't know if this is expected behavior or not but it's certainly not wrong in any sense since your `BlaChild` has type `FC<BlaParentType>` where the `FC` is the `FunctionComponent` interface and that is where the definition takes you.

If I want open `FC` interface I will `go-to-definition` exactrly on `FC` charachters. I don't need open type of component which I try to get.

**Comment by rchl** [comment]
This reproduces with pure Typescript which means that the issue is not in this server.

Feel free to report this at https://github.com/microsoft/TypeScript/issues with this playground testcase: https://www.typescriptlang.org/play?target=1&jsx=1&isolatedModules=true&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgMQMJwL5wGZQiOAcigFMBDAYxkIFgAoeiiAOwGd5UALYAGwBMAXCnQBeOAAoAlHBEA+OAB4+wAG6yFAemVqA3Ixbs4ABTKlmMIWhkTpcxV1584G2XrpA

**Comment by aidos** [comment]
Digging a little deeper into this, VSCode does also return 2 matches - but they default to the first one returned, which is the one you want. I'm wondering if the bigger issue here is actually that the results are being returned in a sensible order (unconfirmed) by Typescript and then sorted incorrectly before being inserted into the quickfix?

![image](https://user-images.githubusercontent.com/91913/123528072-d2a35200-d6dc-11eb-83d1-cbab6752678d.png)

Hacking `locations_to_items` in `runtime/lua/vim/lsp/util.lua` to stop the sorting improves the experience.

**Comment by timsofteng** [comment]
@aidos Thank you very much! In my opinion Ideally it should be fix on server step before it will be in LSP-client.
Can you help me please here?
https://github.com/microsoft/TypeScript/issues/44726

They just closed my issue because I can't provide reproduction steps for vscode... If you can please publish it here or open new issue with more correctly title and explanation.

Otherwise if Microsoft don't wanna fix it then we can discuss to implement this hack which you mentioned to LSP.

**Comment by rchl** [comment]
You should have provided the link to typescriptlang playground that I've posted.

But since https://github.com/microsoft/TypeScript/issues/37816 is exactly about that, there is no need to create new issues.

**Comment by rchl** [comment]
Also, if the order of suggested definition is the main problem for you then, as @aidos mentioned, it seems to be something that seems that is being done by neovim.

**Comment by aidos** [comment]
@timsofteng There's already an issue logged to get it fixed  (https://github.com/microsoft/TypeScript/issues/37816), so the other one should really be closed as a duplicate. Having dug around in the code over there I'm not holding out a huge amount of hope and I think the best solution is to make it a little less jarring in vim.

It currently opens the first match while also showing the quickfix window (https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/handlers.lua#L297..L306). It feels like the main issue is that it sends user focus to quickfix, which is probably easy enough to hack around on the use config side.

**Comment by timsofteng** [comment]
> @timsofteng There's already an issue logged to get it fixed ([microsoft/TypeScript#37816](https://github.com/microsoft/TypeScript/issues/37816)), so the other one should really be closed as a duplicate. Having dug around in the code over there I'm not holding out a huge amount of hope and I think the best solution is to make it a little less jarring in vim.
> 
> It currently opens the first match while also showing the quickfix window (https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/handlers.lua#L297..L306). It feels like the main issue is that it sends user focus to quickfix, which is probably easy enough to hack around on the use config side.

I dunno what is the reason this trouble exist but I have to do `:cclose` after every this kind of `go to definition` action...

**Comment by academo** [comment]
I've been trying to go around this with a custom  `"textDocument/definition"` handler, but I keep seeing the quickfix view open.

Even if I set it to do nothing about it.

```
local log = require 'vim.lsp.log';
local util = require 'vim.lsp.util'

require'lspconfig'.tsserver.setup{
  handlers = {
    ["textDocument/definition"] = function(_, method, result)
      print ("this will print")
      return nil
  }
}
```

**Comment by academo** [comment]
Because this problem happens mainly in a react project and I don't have it with other libraries I end up patching the textDocument/definition handler with some custom logic to not open the quickfix when react.d.ts is involved.

BEAWARE COPYPASTERS: you need to set the "handlers" in your own `tsserver.setup` or this patch will not work. Do not add a new setup for this. 

```
require'lspconfig'.tsserver.setup{
   handlers = {
      ["textDocument/definition"] = function(_, method, result)
      if result == nil or vim.tbl_isempty(result) then
         local _ = vim.lsp.log.info() and vim.lsp.log.info(method, 'No location found')
         return nil
      end


      if vim.tbl_islist(result) then
         vim.lsp.util.jump_to_location(result[1])
         if #result > 1 then
            local isReactDTs = false
            for key, value in pairs(result) do
               if string.match(value.uri, "react/index.d.ts") then
                  print('here?')
                  isReactDTs = true
               end
            end
            if not isReactDTs then
               vim.lsp.util.set_qflist(util.locations_to_items(result))
               vim.api.nvim_command("copen")
               vim.api.api.nvim_command("wincmd p")
            end
         end
      else
         vim.lsp.util.jump_to_location(result)
      end

   end
}
}
```

**Comment by timsofteng** [comment]
> Because this problem happens mainly in a react project and I don't have it with other libraries I end up patching the textDocument/definition handler with some custom logic to not open the quickfix when react.d.ts is involved.
> 
> BEAWARE COPYPASTERS: you need to set the "handlers" in your own `tsserver.setup` or this patch will not work. Do not add a new setup for this.
> 
> ```
> require'lspconfig'.tsserver.setup{
>    handlers = {
>       ["textDocument/definition"] = function(_, method, result)
>       if result == nil or vim.tbl_isempty(result) then
>          local _ = vim.lsp.log.info() and vim.lsp.log.info(method, 'No location found')
>          return nil
>       end
> 
> 
>       if vim.tbl_islist(result) then
>          vim.lsp.util.jump_to_location(result[1])
>          if #result > 1 then
>             local isReactDTs = false
>             for key, value in pairs(result) do
>                if string.match(value.uri, "react/index.d.ts") then
>                   isReactDTs = true
> 			      break
>                end
>             end
>             if not isReactDTs then
>                vim.lsp.util.set_qflist(util.locations_to_items(result))
>                vim.api.nvim_command("copen")
>                vim.api.api.nvim_command("wincmd p")
>             end
>          end
>       else
>          vim.lsp.util.jump_to_location(result)
>       end
> 
>    end
> }
> }
> ```

Thanks.
It works. Hope it will fixed on server side to get rid this weird solution from config...

**Comment by non25** [comment]
After updating to newest neovim workaround above stopped working, this is due [this PR](https://github.com/neovim/neovim/pull/15504).

```diff
 lspconfig.tsserver.setup{
   handlers = {
-    ["textDocument/definition"] = function(_, method, result)
+    ["textDocument/definition"] = function(_, result, params)
       if result == nil or vim.tbl_isempty(result) then
-        local _ = vim.lsp.log.info() and vim.lsp.log.info(method, 'No location found')
+        local _ = vim.lsp.log.info() and vim.lsp.log.info(params.method, 'No location found')
         return nil
       end
```

Adjust like this and it will be fine again.

**Comment by non25** [comment]
Another update

```diff
         end
       end
       if not isReactDTs then
-        vim.lsp.util.set_qflist(util.locations_to_files(result))
+        vim.fn.setqflist(vim.lsp.util.locations_to_items(result))
         vim.api.nvim_command("copen")
-        vim.api.api.nvim_command("wincmd p")
       end
     end
   else
```

Full handler
```lua
lspconfig.tsserver.setup{
  handlers = {
    ["textDocument/definition"] = function(_, result, params)
      if result == nil or vim.tbl_isempty(result) then
        local _ = vim.lsp.log.info() and vim.lsp.log.info(params.method, 'No location found')
        return nil
      end

      if vim.tbl_islist(result) then
        vim.lsp.util.jump_to_location(result[1])
        if #result > 1 then
          local isReactDTs = false
          for key, value in pairs(result) do
            if string.match(value.uri, "react/index.d.ts") then
              isReactDTs = true
              break
            end
          end
          if not isReactDTs then
            vim.fn.setqflist(vim.lsp.util.locations_to_items(result))
            vim.api.nvim_command("copen")
          end
        end
      else
        vim.lsp.util.jump_to_location(result)
      end

    end
  };
}
```

**Comment by johnstonbl01** [comment]
After watching one of TJ's videos ([this one](https://www.youtube.com/watch?v=tAVxxdFFYMU)), I realized that the args could just be passed to the built in handler rather than manually handling the jumping and whatnot. Based on @non25's response and that, here's how I went about solving it:

```lua
local function filter(arr, fn)
  if type(arr) ~= "table" then
    return arr
  end

  local filtered = {}
  for k, v in pairs(arr) do
    if fn(v, k, arr) then
      table.insert(filtered, v)
    end
  end

  return filtered
end

local function filterReactDTS(value)
  return string.match(value.uri, 'react/index.d.ts') == nil
end

lspconfig.tsserver.setup {
  -- other options
  handlers = {
    ['textDocument/definition'] = function(err, result, method, ...)
      if vim.tbl_islist(result) and #result > 1 then
        local filtered_result = filter(result, filterReactDTS)
        return vim.lsp.handlers['textDocument/definition'](err, filtered_result, method, ...)
      end

      vim.lsp.handlers['textDocument/definition'](err, result, method, ...)
    end
  }
}
```

**Comment by acro5piano** [comment]
@johnstonbl01 Thanks, it worked for me!

**Comment by gudnsouza** [comment]
> After watching one of TJ's videos ([this one](https://www.youtube.com/watch?v=tAVxxdFFYMU)), I realized that the args could just be passed to the built in handler rather than manually handling the jumping and whatnot. Based on @non25's response and that realization, here's how I went about solving it:
> 
> ```lua
> local function filter(arr, fn)
>   if type(arr) ~= "table" then
>     return arr
>   end
> 
>   local filtered = {}
>   for k, v in pairs(arr) do
>     if fn(v, k, arr) then
>       table.insert(filtered, v)
>     end
>   end
> 
>   return filtered
> end
> 
> local function filterReactDTS(value)
>   return string.match(value.uri, 'react/index.d.ts') == nil
> end
> 
> lspconfig.tsserver.setup {
>   -- other options
>   handlers = {
>     ['textDocument/definition'] = function(err, result, method, ...)
>       if vim.tbl_islist(result) and #result > 1 then
>         local filtered_result = filter(result, filterReactDTS)
>         return vim.lsp.handlers['textDocument/definition'](err, filtered_result, method, ...)
>       end
> 
>       vim.lsp.handlers['textDocument/definition'](err, result, method, ...)
>     end
>   }
> }
> ```

This solution worked for me on the react/index.d.ts case, but I have another occasion where this happens. When I try to go to definition to a component created by stitches, the same thing occurs, but with the path node_modules/@stitches/react/types/styled-component.ts.

I tried to modify the filter function to cover this case up, but nothing seems to do anything. Since I am a complete noob at lua, it's really hard to determine why is that. Can you give me some help?

**Comment by daliusd** [comment]
Hey, there is `on_list` option in newest neovim (0.8 dev) https://github.com/neovim/neovim/pull/19213

Here is above proposed solution implemented with `on_list`.

```lua
local function filter(arr, fn)
  if type(arr) ~= "table" then
    return arr
  end

  local filtered = {}
  for k, v in pairs(arr) do
    if fn(v, k, arr) then
      table.insert(filtered, v)
    end
  end

  return filtered
end

local function filterReactDTS(value)
  return string.match(value.filename, 'react/index.d.ts') == nil
end

local function on_list(options)
  local items = options.items
  if #items > 1 then
    items = filter(items, filterReactDTS)
  end

  vim.fn.setqflist({}, ' ', { title = options.title, items = items, context = options.context })
  vim.api.nvim_command('cfirst')
end

```

**Comment by gudnsouza** [comment]
> 

Adding to this, the matched string should actually be "%.d.ts", otherwise files ending in "d"won't go to reference e.g. Masthead.tsx.

```lua
local function filterReactDTS(value)
  return string.match(value.uri, '%.d.ts') == nil
end
```

**Comment by zzzachzzz** [comment]
For anyone trying the above workaround, I had to reference `value.targetUri` instead of `value.uri`.

**Comment by rchl** [comment]
It depends on the version of Typescript used whether you'll get `targetUri` or `uri`. So I imagine this can vary per project and ideally the code will use whichever is available.

**Comment by non25** [comment]
And I too took the time to experiment with this stuff. :grin: 

So here's really dumbed down version that does what I want.

```lua
local function patch(result)
  if not vim.tbl_islist(result) or type(result) ~= "table" then
    return result
  end

  return { result[1] }
end

local function handle_gtd(err, result, ctx, ...)
  vim.lsp.handlers['textDocument/definition'](err, patch(result), ctx, ...)
end

return { handle_gtd = handle_gtd }
```

I found out that I've never wanted two definitions pop up in the quickfix list. E.g. when jumping to definition that has type of the same name.

**Comment by cemalokten** [comment]
I am experiencing the same issue, I'd like to use this fix but unsure of how to implement it, my nvim config file structure is as follows:

```
├── after
│   └── plugin
│       ├── colors.lua
│       ├── fugitive.lua
│       ├── fzf.lua
│       ├── lsp.lua
│       ├── treesitter.lua
│       └── undotree.lua
├── init.lua
├── lua
│   └── cemalconfig
│       ├── init.lua
│       ├── packer.lua
│       ├── remap.lua
│       └── set.lua
└── plugin
    └── packer_compiled.lua
```

Where should I place this fix?

**Comment by sarmong** [comment]
`_typescript.goToSourceDefinition`  goes to a definition without listing `.d.ts` files.

[jose-elias-alvarez/typescript.nvim ](https://github.com/jose-elias-alvarez/typescript.nvim) provides an easy way to use it.

**Comment by gudnsouza** [comment]
> For anyone trying the above workaround, I had to reference `value.targetUri` instead of `value.uri`.

Just updated my language-server and that is exactly the solution for the error I was getting.

Mind explaining how you found that out?

**Comment by zzzachzzz** [comment]
> > For anyone trying the above workaround, I had to reference `value.targetUri` instead of `value.uri`.
> 
> Just updated my language-server and that is exactly the solution for the error I was getting.
> 
> Mind explaining how you found that out?

@gudnsouza You can use this handler for `textDocument/definition`, then trigger the go to definition event. You can do this with a mapping or by running the ex command: `:lua vim.lsp.buf.definition()` with your cursor over a function or something.
```lua
lspconfig['tsserver'].setup {
  on_attach = on_attach,
  capabilities = capabilities,
  handlers = {
    ['textDocument/definition'] = function(err, result, method, ...)
      local function dump(o)
         if type(o) == 'table' then
            local s = '{ '
            for k,v in pairs(o) do
               if type(k) ~= 'number' then k = '"'..k..'"' end
               s = s .. '['..k..'] = ' .. dump(v) .. ','
            end
            return s .. '} '
         else
            return tostring(o)
         end
      end
      vim.notify(dump(result))
    end
  },
}
```
Result with my cursor over `<Container>` on line 18:
![image](https://user-images.githubusercontent.com/14324200/223201865-687bf093-56fd-4a6a-a205-e8aa1db4b359.png)

**Comment by olejech** [comment]
<img width="1737" alt="Снимок экрана 2023-04-09 в 21 59 36" src="https://user-images.githubusercontent.com/64708593/230791502-acca2f8d-18b6-43e9-8d01-aec570b4c037.png">
When I use `go to definition` with Telescope I have the same issue.
I use `lsp_definitons` from `telescope.builtin`
```lua
    if lsp_mappings.n.gd then lsp_mappings.n.gd[1] = function() require("telescope.builtin").lsp_definitions() end end
```
I to try filter this declaration file `index.d.ts`, but it's work as hack:
```lua
      lsp_definitions = {
        file_ignore_patterns = { "index.d.ts" },
      },
```

**Comment by damingerdai** [comment]
i met also this issue. my question is that how to close this definition buffer?

**Comment by rounakcodes** [comment]
> i met also this issue. my question is that how to close this definition buffer?

I would like to auto-close the definition buffer once one of the buffers from the list is selected. Thanks.

**Comment by sarmong** [comment]
@damingerdai @rounakcodes `:cclose`

**Comment by rounakcodes** [comment]
@sarmong I meant `auto-close`

**Comment by sarmong** [comment]
@rounakcodes You can create an autocommand for qf buffer type doing anything you want. For example, for me, it also selects a window with `window-picker` plugin.
Here's what I have:

```lua
vim.api.nvim_create_autocmd("FileType", {
  group = "Quickfix",
  pattern = "qf",
  callback = function()
    -- span qf window across all nvim width
    cmd.wincmd("J")

    map("n", "<CR>", function()
      cmd("norm p") -- hide preview from bqf
      local winid = req("window-picker").pick_window()
      if not winid then
        cmd("norm p")
        return
      end
      local cursor = a.nvim_win_get_cursor(0)
      fn.setqflist({}, "r", { idx = cursor[1] })
      a.nvim_set_current_win(winid)
      cmd("cc")
    end, { buffer = 0 })
  end,
})

```

**Comment by acro5piano** [comment]
Neovim 0.11 no longer trigger the global handlers from `vim.lsp.handlers`. It means solutions such as setting custom handlers no longer work.

Instead, you can define a function to open the first item in Quickfix and the close immediately:

```lua
local function go_to_first_definition()
  vim.lsp.buf.definition({
    on_list = function(options)
      if options.items and #options.items > 1 then
        -- Jump to first item. You can do whatever you want here, such as filtering out React d.ts.
        vim.fn.setqflist({}, " ", options) -- Close quicifix list
        vim.cmd("cfirst") -- Jump to first
      elseif options.items and #options.items == 1 then
        local item = options.items[1]
        vim.fn.setqflist({ item }, "r")
        vim.cmd("cfirst")
      else
        print("No definition found")
      end
    end,
  })
end

-- usage
vim.keymap.set("n", "m", go_to_first_definition)
```

https://neovim.io/doc/user/news-0.11.html#_lsp
