### ISSUE TITLE
Unmaintained dev dependency of a dependency causes tsserver errors and prevents start

### ISSUE THREAD

**Issue by dklymenk** [theia-ide/typescript-language-server#217]
Hello,

I am working on https://github.com/Expensify/Expensify.cash project that has an issue with this language server. It just plain doesn't start. To reproduce, just clone the project, run `npm i` and open a project in your editor.

Here is a relevant log entry:
```
[ ERROR ] 2021-06-06T23:41:13+0300 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:410 ]     "[tsserver] internal/modules/cjs/loader.js:883\n  throw err;\n
 ^\n\nError: Cannot find module '_debugger'\nRequire stack:\n- /home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver.js\n- /home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:725:27)\n    at Module.require (internal/modules/cjs/loader.js:952:19)\n    at require (internal/modules/cjs/helpers.js:88:18)\n    at /home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver.js:39473:25\n    at /home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver.js:39689:7\n    at Object.<anonymous> (/home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver.js:39690:3)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver.js',\n    '/home/dklymenk/Documents/upwork/Expensify.cash/node_modules/tsc/bin/tsserver'\n  ]\n}\n"
 ```
 
 Manually deleting the `tsc` node module fixes the problem. I assume it is a dev dependency used to compile the ts or something like that for another dependency (https://github.com/plaid/react-native-plaid-link-sdk), so I don't need it to be installed or indexed whatsoever.
 
 So, I guess what I'm asking is if there is a way to add some ignore list, so tsserver doesn't index entire `node_modules` folder, preventing it from throwing an error and failing to start. Or maybe there is any other solution that doesn't involve manually doing `rm -rf node_modules/tsc` after every `npm i`.
 
 I'm using nvim native lsp client, if that's relevant to the issue.
 
 Thanks.

**Comment by rchl** [comment]
- This project uses `yarn`. When you use `npm i` you might get different versions than the ones pinned in this project and thus issues
- For running the server you only want to install production dependencies. devDependencies are only needed to compile the server. Not having dev dependencies might solve your issue also.
- Why don't you use the `typescript-language-server` package from `npm` and instead you are cloning this directly? The published package doesn't contain any unnecessary dependencies. It doesn't even contain the `typescript` dependency.
- I don't even see `tsc` module when installing all dependencies (using yarn at least).

**Comment by dklymenk** [comment]
I'm sorry if my description of the problem was confusing or misleading to you, but none of your bullet-points are relevant to the problem I have outlined in the original post.

> Why don't you use the typescript-language-server package from npm and instead you are cloning this directly? The published package doesn't contain any unnecessary dependencies. It doesn't even contain the typescript dependency.

I am not sure what led to believe I'm cloning this project, but as mentioned in the issue I am working on https://github.com/Expensify/Expensify.cash. My `typescript-language-server` executable is installed globally via `npm` just like this project's README says.

 > For running the server you only want to install production dependencies. devDependencies are only needed to compile the server. Not having dev dependencies might solve your issue also.
 
 The devDependencies are a requirement for working with a react project: babel, eslint, jest, webpack, etc. Not installing devDependencies is not an option.
 
 > I don't even see tsc module when installing all dependencies (using yarn at least).
 
As I said in the original post, `tsc` is a devDependency of https://github.com/plaid/react-native-plaid-link-sdk which is a dependency of https://github.com/Expensify/Expensify.cash (the actual project I am working on). Once again, I am not cloning and installing dependencies for typescript-language-server.

> This project uses yarn. When you use npm i you might get different versions than the ones pinned in this project and thus issues

The package manager is irrelevant. Regardless of whether one is using npm or yarn, if you are not doing a prod install (no devDependencies), all the dependencies and devDependencies with be recursively installed. As far as I can tell there is no way to install only root devDependencies with npm or yarn.

-----------------------------------------------------------------------------------------------------

So, please give it a try yourself.

```sh
git clone git@github.com:Expensify/Expensify.cash.git
cd Expensify.cash
npm i # or yarn
```

Then start your editor or any other mean you test your LSP server with, and try to perform any action (jump to definition, show references, trigger auto-completion). None of these will work, because the server is crashed. See my original post for the relevant line in the logs.

Now if you manually delete `rm -rf node_modules/tsc`, restart your editor or restart the LSP server, all the actions will work.

----------------------------------------

The reason I think this should be resolved on LSP server level is because it's a common configuration option among LSP servers to allow skipping certain folders during indexing. Here is a link to this configuration option in [Phpactor](https://phpactor.readthedocs.io/en/master/reference/configuration.html#indexer-exclude-patterns) an LSP server for PHP. 

Also I've seem people using VSCode as example where everything works in other issues, so I'll do it here too. This issue is not reproducible in VSCode for me. I think the server there just doesn't crash if it encounters an unhanded error during indexing.

Please, let know, if any of this is unclear, I'll try my best to explain it.

Also, if you can point me into a file where an indexer is implemented in this project, I might try implementing a fix myself. Even though I'm not very confident with typescript, I am motivated to get this issue resolved.

**Comment by rchl** [comment]
I see what you mean now.

This server tries to resolve the `tsserver` from the local project which is at `node_modules/.bin/tsserver` and has this content:

```
#!/usr/bin/env node
require('./tsserver.js')
```

This gets resolved to `node_modules/tsc/bin/tsserver.js` which is unfortunate because `tsc` is, I guess, a very old equivalent of modern `typescript` package.

This results in an error like:

```

LSP-typescript: [tsserver] internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '_debugger'
Require stack:
- /Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver.js
- /Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver.js:39473:25
    at /Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver.js:39689:7
    at Object.<anonymous> (/Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver.js:39690:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver.js',
    '/Users/me/workspace/temp/Expensify.cash/node_modules/tsc/bin/tsserver'
  ]
}
```

It's not possible for the server to "ignore" it since it's not the server that is doing the resolving (the `resolve` call) of those paths. It's the node itself.

What you can do yourself about this case though is to point the server to the correct tsserver version using the `tsserver-path` cli option - https://github.com/theia-ide/typescript-language-server/blob/89d22580fc64fbebd12ebd4b88bdef38f76ddf1c/server/src/cli.ts#L24-L24

I'm not sure if there is any generic solution that could be applied in the server.
Since this is pretty much a corner case, it might be OK to ignore it and expect the user to just handle it with manually overriding the tsserver path per-project.

**Comment by dklymenk** [comment]
Wow, I didn't realize it works like that. Thanks for your help and research. I did `npm install -g typescript`, added `--tsserver-path=tsserver` to my LSP config, and the issue is fixed now.

Thank you very much.

I actually see what you mean here: https://github.com/theia-ide/typescript-language-server/blob/89d22580fc64fbebd12ebd4b88bdef38f76ddf1c/server/src/lsp-server.ts#L77-L81
The `tsserver` is getting symlinked to `tsc`  in that project :facepalm: 

To anyone that stumbles upon this issue in the future, you don't need to install `typescipt` globally, since you already have it installed as a dependency for `typescript-language-server`. If you're using nvim lsp, you most likely have the tsserver executable at `~/.local/share/nvim/lspinstall/typescript/node_modules/typescript/lib/tsserver.js`, so you can use this snippet below as cmd for `lspconfig`:
```lua
    cmd = {DATA_PATH .. "/lspinstall/typescript/node_modules/.bin/typescript-language-server", "--stdio", "--tsserver-path=" .. DATA_PATH .. "/lspinstall/typescript/node_modules/typescript/lib/tsserver.js"},
```
