### ISSUE TITLE
JSDoc support

### ISSUE THREAD

**Issue by niksy** [theia-ide/typescript-language-server#236]
I’m trying to use language server with Sublime Text but it doesn’t seem to be handling type definitions inside JSDoc comments. Same feature works OK in [official TypeScript plugin for Sublime Text](https://github.com/microsoft/TypeScript-Sublime-Plugin).

Is this something related to language server or [Sublime Text plugin](https://github.com/sublimelsp/LSP-typescript)?

![Screen Shot 2021-07-13 at 09 05 52](https://user-images.githubusercontent.com/389286/125406838-8c770f80-e3b9-11eb-9f8c-2ca35b6277d3.png)

**Comment by rchl** [comment]
Maybe you can share a project that reproduces?

I'm using the same editor+server combination daily and it works just fine here.

**Comment by niksy** [comment]
Here is the video, I hope it can explain it:

https://user-images.githubusercontent.com/389286/125593273-2a9d1432-03eb-4540-936f-b4ee0c306786.mp4

**Comment by predragnikolic** [comment]
I also use Sublime Text and [LSP-typescript](https://github.com/sublimelsp/LSP-typescript), 
but that is not how it works for me:

For me it works fine:
![Kapture 2021-07-14 at 11 44 26](https://user-images.githubusercontent.com/22029477/125601208-3c105cb6-2779-4862-92c0-74fa8cee4135.gif)

**Comment by niksy** [comment]
Huh, now it works. I guess that depends on how the server is working. I think I managed to "fix" it in some instances by restarting LSP server. Will see if this happens again and in which cases.

**Comment by rchl** [comment]
The `JSDoc types may be moved to TypeScript types` diagnostic that shows up in your video should only be shown in TS files. The only way I can think of how it happened in your case is if you create a *.ts file first and then renamed it to `index.js`.

**Comment by niksy** [comment]
@rchl could be, and also I was switching between TypeScript/JavaScript syntax highlighting so that could count also.
