### ISSUE TITLE
Please do not depend on exact typescript version

### ISSUE THREAD

**Issue by Swatinem** [theia-ide/typescript-language-server#24]
Currently, the typescript dependency is at a fixed version: https://github.com/theia-ide/typescript-language-server/blob/f9be84ff8deeae06169c8a69df4de0de307e9ba9/package.json#L35

This is bad for a few reasons:
* it duplicates typescript on disk, which has a whooping X MB on disk (which is a WTF on its own)
* you won’t get newer strict warnings in your IDE when you upgrade the typescript version inside your project.
* it is obviously a maintenance burden, since you would have to bump and release on every upstream typescript release.

**Comment by prabirshrestha** [comment]
typescript package is only used for `typescript/lib/protocol` typings file. The actual tsserver is not used from that package. The logic can be found here https://github.com/theia-ide/typescript-language-server/blob/a8432a822da744330dd85e024f4fce1c5dfa3e9e/src/lsp-server.ts#L69-L88 

Or you could also force the tsserver to be what you want.
```
    --tsserver-path <path>                 Specifiy path to tsserver. example: --tsserver-path=tsserver
```

So only this would hold true.
> it duplicates typescript on disk, which has a whooping X MB on disk (which is a WTF on its own)

**Comment by Swatinem** [comment]
Thanks for the quick answer.

> typescript package is only used for typescript/lib/protocol typings file.

Well then there is no reason to have it as a runtime dependency at all. :-)

**Comment by svenefftinge** [comment]
https://github.com/theia-ide/typescript-language-server/pull/25
