### ISSUE TITLE
Is typescript-language-server support standard lsp format with two '\r\n'

### ISSUE THREAD

**Issue by hasegetc** [theia-ide/typescript-language-server#240]
according to this page:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#headerPart
the standard lsp format with two '\r\n'，but, in the demo, I find the typescript-language-server message with out '\r\n',
is it support that?
![image](https://user-images.githubusercontent.com/5785979/127623661-461e4ea6-f339-4f32-9222-2eb560965a24.png)

**Comment by rchl** [comment]
The server communicates with the client using stdio which follows the spec. While I haven't verified that it does follow the spec, it would likely not work with many editors if it didn't.

What you have in the screenshot is a higher level communication flow using web socket. It's a layer on top of the original communication flow and is just specific to the example editor that is included in the repo.
