### ISSUE TITLE
Should typescript npm package be a dependency?

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/typescript-language-server#29]
ATM it's a dev dependency. 

I think it would help with https://github.com/theia-ide/theia-apps/issues/29

**Comment by prabirshrestha** [comment]
You need to have typescript installed locally by `npm install typescript` or install it global and make it available in environment path `npm install -g typescript`.

In order to reproduce unncessary typescript download langserver doesn't ship with typescript compiler.

**Comment by marcdumais-work** [comment]
Will do, thanks @prabirshrestha
