### ISSUE TITLE
buffer stdio.write

### ISSUE THREAD

**Issue by prabirshrestha** [theia-ide/typescript-language-server#33]
Seems like vim has race conditions. Would it be possible to buffer stdout.write in chunks? More information at https://github.com/vim/vim/issues/2548

**Comment by svenefftinge** [comment]
Yes. PRs are welcome :)

**Comment by prabirshrestha** [comment]
Both vim-lsp and typescript language server now support incremental changes, so it no longer hangs. I'm closing this since I no longer require this feature.
