### ISSUE TITLE
Usage with Sublime LSP

### ISSUE THREAD

**Issue by james2doyle** [theia-ide/typescript-language-server#45]
I managed to get this working with *plain javascript* in Sublime using the [tomv564/LSP plugin](https://github.com/tomv564/LSP).

![demo with plain JS](https://cl.ly/140l1A402F01/Screen%20Recording%202018-07-04%20at%2009.13%20PM.gif)

Here are the settings:

```json
{
  "jsts": {
    "command": ["typescript-language-server", "--stdio"],
    "enabled": true,
    "languageId": "javascript",
    "scopes": ["source.js"],
    "syntaxes": ["Packages/JavaScript/JavaScript.sublime-syntax"]
  }
}
```

This works with plain JavaScript with no `tsconfig` file. It will also parse the `@types` in your `node_modules`.

Basically, this means you can get a much better experience in Sublime with javascript using this language server and the LSP plugin.

For general TypeScript usage, the Sublime TypeScript plugin seems to do a fine job. But for plain javascript project (not written in `.ts` files) this is excellent.

I wasn't sure where to put this as it isn't an issue. Just that I found this project while trying to get things working in Sublime. Sorry to spam your issue list.

**Comment by svenefftinge** [comment]
> I wasn't sure where to put this as it isn't an issue. Just that I found this project while trying to get things working in Sublime. Sorry to spam your issue list.

I don't know either, but I don't think many sublime users will tumble over it here. :)

Thanks for sharing, anyway!

**Comment by kud** [comment]
It doesn't work here:

```
"typescript-language-server":
    {
      "command": ["typescript-language-server", "--stdio"],
      "enabled": true,
      "languages": [
      {
        "languageId": "javascript",
        "scopes": [
          "source.js",
          "source.jsx"
        ],
        "syntaxes": [
          "Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax",
          "Packages/Babel/JavaScript (Babel).sublime-syntax",
          "Packages/JavaScript/JavaScript.sublime-syntax"
        ]
      },
      {
        "languageId": "typescript",
        "scopes": [
          "source.ts",
          "source.tsx"
        ],
        "syntaxes": [
          "Typescript"
        ]
      }]
    },
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/655838/63254244-aeba8e00-c273-11e9-89b2-cb88832daf17.png">

**Comment by kud** [comment]
Alright, alright. As I don't use typescript for the moment, I didn't install "typescript" via `npm install -g typescript`

I only use this server for javascript.

By installing it, it's now fixed.
