### ISSUE TITLE
VS Code Language Client

### ISSUE THREAD

**Issue by jchurch33** [theia-ide/typescript-language-server#55]
So I'm interested in using this language server for VS Code extensions development (which seems to be one of the natural use-cases) but try as I might I can't seem to get this server to run with VS Code's language client. I can't find any examples of others doing it either. I was hoping you could either point me to one or give me some pointers or something of that sort

**Comment by svenefftinge** [comment]
Why would you want to do that? VS Code comes with excellent typescript support out of the box.

**Comment by jchurch33** [comment]
Me and my team have been developing a VS Code extension for Typescript but we need to be able to get references and definitions from the Typescript Server. We haven't found any way to speak directly to the native typescript server so we want to run our own. Right now the way we are doing it is pretty hacky, so we wanted to use the LanguageClient class.

**Comment by svenefftinge** [comment]
There is no example, because VS Code comes with its own TypeScript extension.  
But it should work just like with any other language server.

**Comment by mattlyons0** [comment]
To piggyback off this I hacked together an Atom Language Client so its definitely possible for VS Code. https://github.com/mattlyons0/ide-typescript-theia

**Comment by akosyakov** [comment]
@mattlyons0 Cool, to see it in Atom. You should open a PR against https://github.com/atom/ide-typescript :)

**Comment by keyboardDrummer** [comment]
Seems like this issue can be closed, right?

**Comment by jchurch33** [comment]
@keyboardDrummer yes! I understand what I was missing before
