### ISSUE TITLE
reload projects

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/typescript-language-server#57]
We should reload projects if tsconfig/jsconfig are changed or installed typescript version in projects's node_modules. Maybe also have a command to let a user to reload manually, i.e. if typescript is installed globally.

**Comment by keyboardDrummer** [comment]
Doesn't tsserver monitor the `*config` files for changes, and reload the project when they change?

See [the code](https://github.com/Microsoft/TypeScript/blob/master/src/server/editorServices.ts#L1574).

**Comment by akosyakov** [comment]
@keyboardDrummer thanks for reminding, i've observed the same recently, perhaps only with the older version
