### ISSUE TITLE
Have a change log for each release

### ISSUE THREAD

**Issue by dylan-chong** [theia-ide/typescript-language-server#61]
It would be nice to know what changed when a new version is released. I don't mind if you don't create a change log for the current release, as long as they are created for future releases

**Comment by dylan-chong** [comment]
also see this https://keepachangelog.com/en/0.3.0/#what-s-the-point-of-a-change-log

**Comment by akosyakov** [comment]
@dylan-chong yes, it would be useful, do you want to submit an initial PR?

**Comment by dylan-chong** [comment]
I'm not sure what would be in it. Probably not a good idea is me to do it

**Comment by akosyakov** [comment]
ok, will create an initial after merging https://github.com/theia-ide/typescript-language-server/pull/62 and releasing a new patch version

**Comment by akosyakov** [comment]
Added https://github.com/theia-ide/typescript-language-server/blob/master/CHANGELOG.md with descriptions for last 3 versions
