### ISSUE TITLE
The contents of documents in `this.openedDocumentUris` are never updated

### ISSUE THREAD

**Issue by keyboardDrummer** [theia-ide/typescript-language-server#63]
On didChange requests, it seems like you don't update the contents of the document you store in memory, see [the code](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L264).

Since you are using the document contents in several places, this seems like it would lead to bugs. 

This is somewhat confirmed because I'm seeing faulty behavior when sending non-incremental didChange requests, which trigger calls to the contents of the stored document, [here](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L276).

**Comment by akosyakov** [comment]
Looks like a bug for sure. PRs are very welcomed. One can use [TextDocument.applyEdits](https://github.com/Microsoft/vscode-languageserver-node/blob/371587767e928ec8818383d7f2876fb0a65f7ba6/types/src/main.ts#L2283) to implement it.

**Comment by keyboardDrummer** [comment]
Awesome to see such a quick fix :)
