### ISSUE TITLE
Allow a client to configure typescript.tsdk (similar to VS Code)

### ISSUE THREAD

**Issue by keyboardDrummer** [theia-ide/typescript-language-server#64]
Have you considered using the [Session](https://github.com/Microsoft/TypeScript/blob/master/src/server/session.ts) class inside the LSP server process, instead of starting a separate tsserver process?

Pros:
- Less processes, less communication overhead
- The LSP server now has access to the internal state of tsserver, so you don't have to store duplicate state in the LSP server, which is done [here](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L51) to store the state of open documents. Note that I believe this is done incorrectly, see [this issue](https://github.com/theia-ide/typescript-language-server/issues/63).

Cons:
- Less reliable contract of the dependency, since tsserver's contract is less likely to change than that of `Session`. This also means that you should always use the `Session` class that is bundled with the `typescript-language-server` installation, so you know for sure that it works well. The downside here is that you won't get automatic TypeScript upgrades if the user installs a newer global version of TypeScript. However, I think that behavior was a bit risky to begin with, since the contract of tsserver can also change.

**Comment by akosyakov** [comment]
I don't think it is a good idea to rely on own tsserver, as you mentioned it won't be forward-compatible.

**Comment by keyboardDrummer** [comment]
Well, do you think tsserver tries to be backwards compatible? I don't see what guarantee you have that it will be. It seems dangerous to me to just pick a tsserver from the environment as you do [here](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L70), since it might be a newer version than what you have tested against.

A related issue is that if you support LSP's [workspaceFolders](https://microsoft.github.io/language-server-protocol/specification#workspace_workspaceFolders) feature, then you won't be able to use the tsserver from the project's node_modules, as you do [here](https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L75), since there will be multiple projects. See [this issue](https://github.com/theia-ide/typescript-language-server/issues/66).

Anyways if you strongly oppose this suggestion, then feel free to close this issue.

**Comment by akosyakov** [comment]
> Well, do you think tsserver tries to be backwards compatible?

We are trying to align behavior with the VS Code extension. If they can assume that tsserver is backward compatible, I think we can too.

> A related issue is that if you support LSP's workspaceFolders feature, then you won't be able to use the tsserver from the project's node_modules, as you do here, since there will be multiple projects. See this issue.

In VS Code a user is responsible to decide which tsserver should be used via workspace configurations. We can rely on LSP configurations capabilities as well. In the case, if a configuration is not provided we can either prompt a user via the custom request or a fall-back to the first tsserver.

**Comment by akosyakov** [comment]
It's already possible with `--tsserver-path` option. The tool can decide which tsserver to use and whether to let a user switch between them.
