### ISSUE TITLE
Incorrect selection range for the `DocumentSymbol`

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/typescript-language-server#74]
https://github.com/theia-ide/typescript-language-server/blob/acd16435dd307e06281af508732dcce23a67e9b8/server/src/document-symbol.ts#L33

The range is not equal to the selection range.

`selectionRange` is from Outline to Editor.
`range` is from Editor to Outline.

See the attached screenshot:
![screencast 2018-09-14 16-43-16](https://user-images.githubusercontent.com/1405703/45557296-89d8c200-b83d-11e8-8d65-5bcd8cbcf187.gif)

When selecting an item in the Outline, it should only highlight the name of the symbol not the entire range of the symbol

**Comment by akosyakov** [comment]
We could try to make use of [NavigationTree.nameSpan](https://github.com/Microsoft/TypeScript/blob/24a5bdd1b165f0cc5211cd786d1782eadf6117d2/src/services/types.ts#L472) if it is present.

**Comment by akosyakov** [comment]
@keyboardDrummer thanks! checked in Theia it works nicely with ts 3, for older versions it does not work
