### ISSUE TITLE
Can't use TSX support in LanguageClient-neovim

### ISSUE THREAD

**Issue by cormacrelf** [theia-ide/typescript-language-server#90]
The [languageId -> TS/TSX function](https://github.com/theia-ide/typescript-language-server/blob/d1a9a632a3e5e5ad5404a639ee7badcfb905d8f1/server/src/lsp-server.ts#L260) only supports the languageIds used in VSCode. They are `typescript`, and `typescriptreact` for TSX.

In Vim, however, the convention is to use `typescript.tsx`, which means editing tsx files either doesn't work (`typescript.tsx`), or spews forth thousands of syntax errors (with just `typescript`). That option isn't configurable in LanguageClient-neovim, it must use the `&filetype` variable.

Could that function be amended to recognise the Vim form as well? Same goes for `javascript.jsx`.

**Comment by alextes** [comment]
@cormacrelf are you sure? The following appears to work fine for me:
```vim
let g:LanguageClient_serverCommands = {
      \ 'typescript': ['~/.node-bin/javascript-typescript-langserver', '--stdio'],
      \ 'typescript.tsx': ['~/.node-bin/javascript-typescript-langserver', '--stdio'],
      \}
```

**Comment by alextes** [comment]
Seems to be working fine too @cormacrelf . Did you try logging the client and server output?
<img width="620" alt="screen shot 2019-01-03 at 23 33 53" src="https://user-images.githubusercontent.com/2011351/50665207-13a8c880-0fb0-11e9-9d72-9b060e509c56.png">
`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ESNEXT",
    "module": "commonjs",
    "jsx": "preserve",
    "strict": true,
    "allowSyntheticDefaultImports": false,
    "esModuleInterop": true
  }
}
```

**Comment by BenoitZugmeyer** [comment]
I have the same issue, but I guess this is because `leafgarland/typescript-vim` does not set the filetype to `typescript.tsx` yet, see https://github.com/leafgarland/typescript-vim/pull/140

**Comment by everett1992** [comment]
Why does the file type need to be `typescript.tsx` to enable tsx support from the language server? I was bit by this because I use `leafgarland/typescript-vim` so my filetype was `typescript`.

**Comment by tsujp** [comment]
I'm having problem using typescript react with sublime LSP also, any fixes available nothing in this issue worked.

**Comment by JasonMFry** [comment]
@tsujp Add this line to your vimrc:

`autocmd BufNewFile,BufRead *.tsx setlocal filetype=typescript.tsx`.

I found this suggestion [here](https://medium.com/@s1n7ax/neovim-for-typescript-react-development-fdc7082c8a78). It did the trick.

If you want to know more about what the line does, search the help docs for autocmd `:h autocmd`. Basically any time a new file is being created or a file is being read, and it's a tsx file, it sets the filetype to typescript.tsx. You could do something silly and change css filetypes to js to see what happens.

**Comment by NikosEfthias** [comment]
alternatively adding a modeline is also an option instead of a autocmd I dont event have typescript.vim I dont really know why I am having this issue tho :D

**Comment by rchl** [comment]
The clients have to adjust to languageIds supported by this server, not the other way around. The IDs are pretty standardized these days across clients.

As for Sublime Text, you might just want to assign the TSX syntax to all typescript files. That shouldn't cause issues for plain TS files.
