### ISSUE TITLE
Issue with documentHighlight feature

### ISSUE THREAD

**Issue by PyvesB** [theia-ide/typescript-language-server#94]
Hello,

I'm indirectly using this language server through the [Eclipse WildWebDeveloper tool](https://github.com/eclipse/wildwebdeveloper). I encountered an issue with selection highlighting which we think may be caused by the typescript language server itself (more information [here](https://github.com/eclipse/wildwebdeveloper/issues/104)).

Here is the request that is sent to the server:
```
{
   "jsonrpc":"2.0",
   "id":"12",
   "method":"textDocument/hover",
   "params":{
      "textDocument":{
         "uri":"file:///[...]/popup.js"
      },
      "uri":"file:///[...]/popup.js",
      "position":{
         "line":95,
         "character":32
      }
   }
}
```

_popup.js_ is a file checked out locally, but corresponds to the Javascript document located in [this repository](https://github.com/PyvesB/night-video-tuner/blob/master/popup/popup.js). I'm trying to highlight the `storageObj` variable.

However, the response from the server comes back empty:
```
{
   "jsonrpc":"2.0",
   "id":"12",
   "result":{
      "contents":[

      ]
   }
}
```

Is this to be expected?

Thanks in advance for your help.

Cheers,

Pyves

**Comment by princemaple** [comment]
highlights seem to consistently return empty array, could someone take a look?

In my case it's SublimeText & [LSP](https://packagecontrol.io/packages/LSP).
Some logs below, numbered with internal request id
```
2 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 26, 'character': 30}}
2 {'result': [], 'jsonrpc': '2.0', 'id': 2}
3 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 27, 'character': 36}}
3 {'result': [], 'jsonrpc': '2.0', 'id': 3}
Unable to fetch update url contents
4 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 27, 'character': 15}}
4 {'result': [], 'jsonrpc': '2.0', 'id': 4}
5 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 27, 'character': 19}}
5 {'result': [], 'jsonrpc': '2.0', 'id': 5}
6 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 26, 'character': 17}}
6 {'result': [], 'jsonrpc': '2.0', 'id': 6}
7 textDocument/documentHighlight {'textDocument': {'uri': 'file:///[...].component.ts'}, 'position': {'line': 27, 'character': 21}}
7 {'result': [], 'jsonrpc': '2.0', 'id': 7}
```

The places I put the caret are supposed to have several symbol matches in the same file.

**Comment by PyvesB** [comment]
So, I've looked into this some more and did some debugging. I believe the line as fault is the following:
https://github.com/theia-ide/typescript-language-server/blob/ca32f72e347364a12092fd41e62800db5834d661/server/src/lsp-server.ts#L761

`item.file` is the response from the underlying Typescript Server. It seems to systematically return paths with POSIX delimiters. On the other hand, when `uriToPath` is called to create the `file` variable, `fsPath` is used, with platform specific path delimiters. In other words, the comparison will always fail on Windows, and the result will always be empty.

I'll prepare a pull request to fix this.

**Comment by princemaple** [comment]
My DX will be massively improved if this could be fixed :) although I've got used to not having it.

**Comment by princemaple** [comment]
hi @akosyakov it would be super awesome if you could make a release with this change 😄

**Comment by PyvesB** [comment]
Maybe @svenefftinge would be able to help give us some more information about the next release? 😉

**Comment by PyvesB** [comment]
Sent a small [Tweet around](https://twitter.com/_Pyves/status/1226121367961075712) as this seems to have been forgotten. There are other pending pull requests, would be great to get them through as well!

**Comment by princemaple** [comment]
Maybe time to consider a community fork for release purpose only.
